### ISSUE TITLE
群发消息不发送的bug

### ISSUE THREAD

**Issue by Lao-CCCCC** [Frica01/WeChat-mass-msg#14]
在群发消息的时候，在微信搜索框搜出昵称并进入聊天框后，如果收到别的微信消息，就不会复制需要发送的内容到聊天框（个人观察发现是当前搜索的昵称在复制发送内容前被新消息挤掉了一样）
![微信图片_20240307114932](https://github.com/Frica01/WeChat-mass-msg/assets/162533810/7e615167-c39f-4d17-ac05-4467917629d3)

**Comment by Frica01** [comment]
小小问题,拿捏
