### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ericchenchen2023** [Frica01/WeChat-mass-msg#8]
安装后的界面和你的不一样
![a](https://github.com/Frica01/WeChat-mass-msg/assets/148447365/a36c9691-6802-4719-ba97-e219bbdf34a1)

输入发送消息和昵称后发送报错，查看代码报错如下：
 add_remark_name = True if self.cbox_add_remark_name.checkState().value else False     
AttributeError: 'PySide6.QtCore.Qt.CheckState' object has no attribute 'value'

**Comment by Frica01** [comment]
可能是pyside6版本的差异，现已在requirements.txt指定所有模块的版本~

**Comment by Frica01** [comment]
> 安装后的界面和你的不一样 ![a](https://private-user-images.githubusercontent.com/148447365/291028288-a36c9691-6802-4719-ba97-e219bbdf34a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTM3NzQsIm5iZiI6MTcwMjc5MzQ3NCwicGF0aCI6Ii8xNDg0NDczNjUvMjkxMDI4Mjg4LWEzNmM5NjkxLTY4MDItNDcxOS1iYTk3LWUyMTliYmRmMzRhMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwNjExMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2RlYjBkMWUxNTY1ZGJjN2RiODJjYzlmZmU5OTIwYTJiZDU2NGRjODc0MmM5MmZkOTI3MThlMTY2NjE0YTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oDTsJhS-8TZtxQ-Ep0RltBkH3R2HTVj1qODvfCh6qZw)
> 
> 输入发送消息和昵称后发送报错，查看代码报错如下： add_remark_name = True if self.cbox_add_remark_name.checkState().value else False AttributeError: 'PySide6.QtCore.Qt.CheckState' object has no attribute 'value'

界面不同是因为GUI改了一下，但是readme.md没改
